/**
 * server_dotnet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    readonly street1?: string | null;
    readonly zipCode?: string | null;
    readonly city?: string | null;
    readonly country?: string | null;
}

